# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: marvan-d <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/19 13:10:58 by marvan-d          #+#    #+#              #
#    Updated: 2019/09/19 13:11:00 by marvan-d         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc error_checking.c error_checking_helper.c -Wall -Werror -Wextra ../libft/libft.a

clean:
	rm a.out

